// Generated by MODEX Version 2.11 - 3 November 2017
// ‫جۆمعه آخشامی ۰۹ سپتامبر ۲۱، ساعات ۱۸:۱۶:۵۳ (+0430)‬ from example.c

active proctype p_main()
{
L_0:
    do
    :: true;
	int flag;
	chan out_p_f1 = [0] of {int};
        run p_f1(out_p_f1);
	out_p_f1 ? flag;
    goto L_0;
    :: !1 -> break
    od;
    goto Return;
Return: skip;
}
proctype p_f1(chan out_p_f1)
{
int i;
    i=1;
L_1:
    do
    :: i<10;
	int flag;
	chan out_p_f2 = [0] of {int};
        run p_f2(out_p_f2);
	out_p_f2 ? flag;
i++;
    goto L_1;
i++;
    :: !(i<10) -> break
    od;
    goto Return;
Return: skip;
out_p_f1 ! 1;
}
proctype p_f2(chan out_p_f2)
{
    int flag;
    chan out_p_f3 = [0] of {int};
    run p_f3(out_p_f3);
    out_p_f3 ? flag;
    goto Return;
Return: skip;
out_p_f2 ! 1;
}
proctype p_f3(chan out_p_f3)
{
    int flag;
    chan out_p_f1 = [0] of {int};
    run p_f1(out_p_f1);
    out_p_f1 ? flag;
    goto Return;
Return: skip;
out_p_f3 ! 1;
}


