// Generated by MODEX Version 2.11 - 3 November 2017
// ‫شنبه ۱۱ سپتامبر ۲۱، ساعات ۱۲:۲۷:۳۰ (+0430)‬ from 2_pointers.c

bool lck_p_main_ret;
bool lck_p_main;
chan ret_p_main = [1] of { pid };
chan exc_cll_p_main = [0] of { pid };
chan req_cll_p_main = [1] of { pid };
 c_state "int  ***** a" "Local p_main"
 c_state "int  * p" "Local p_main"
 c_state "int  * q" "Local p_main"
 c_state "int  * i" "Local p_main"
 c_state "int  * j" "Local p_main"
 c_state "int  * k" "Local p_main"
active proctype p_main( )
{
int x = 12;
int y = 34;
int z;
int w;
pid lck_id;
    c_code { Pp_main->p=(&(Pp_main->z)); };
    c_code { Pp_main->q=(&(Pp_main->x)); };
    c_code { Pp_main->x=56; };
    c_code [Pp_main->q && Pp_main->p] { (*Pp_main->p)=(*Pp_main->q); };
    c_code { Pp_main->i=Pp_main->p; };
    c_code { Pp_main->p=(&(Pp_main->y)); };
    c_code [Pp_main->a && (*Pp_main->a) && (*((*Pp_main->a))) && (*((*((*Pp_main->a)))))] { (*((*((*((*Pp_main->a)))))))=Pp_main->i; };
    c_code [Pp_main->a && (*Pp_main->a) && (*((*Pp_main->a))) && (*((*((*Pp_main->a)))))] { Pp_main->j=(*((*((*((*Pp_main->a))))))); };
    c_code { Pp_main->i=Pp_main->q; };
Return: skip;
}
