// Generated by MODEX Version 2.11 - 3 November 2017
// ‫جۆمعه آخشامی ۰۹ سپتامبر ۲۱، ساعات ۱۸:۱۶:۵۳ (+0430)‬ from example.c

active proctype p_main()
{
L_0:
    do
    :: true;
        c_code { f1(); };
    goto L_0;
    :: c_expr { !1 }; -> break
    od;
    goto Return;
Return: skip;
}
active proctype p_f1()
{
int i;
    c_code { Pp_f1->i=1; };
L_1:
    do
    :: c_expr { (Pp_f1->i<10) };
        c_code { f2(); };
c_code { Pp_f1->i++; };
    goto L_1;
c_code { Pp_f1->i++; };
    :: c_expr { !(Pp_f1->i<10) }; -> break
    od;
    goto Return;
Return: skip;
}
active proctype p_f2()
{
    c_code { f3(); };
    goto Return;
Return: skip;
}
active proctype p_f3()
{
    c_code { f1(); };
    goto Return;
Return: skip;
}
